# Generated by Django 3.2.20 on 2023-08-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
