# Generated by Django 3.2.20 on 2023-08-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_home_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
